homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long

  auth_providers:
   - type: homeassistant
   - type: legacy_api_password

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 80
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml
  customize_glob:
    "sensor.dark_sky_*":
      hidden: true
#    "sensor.forecast_*":
#      hidden: true

  packages: !include_dir_named packages

# Show links to resources in log and frontend
# introduction:

# Enable the auth component
auth:

# Enables the frontend
frontend:

#python_script:

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret conf_url

mqtt:
  broker: core-mosquitto
#  username: !secret mqttUser
  password: !secret mqttPass
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: "tele/hass1/LWT"
    payload: "Online"
    qos: 1
    retain: true
  will_message:
    topic: "tele/hass1/LWT"
    payload: "Offline"
    qos: 1
    retain: true

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret hass_url
  ssl_profile: intermediate
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  api_password: !secret ha_dash_pw
  trusted_networks:
    - 127.0.0.1
    - 172.30.0.0/16
    - ::1
    - !secret duck_network
  ip_ban_enabled: true
  login_attempts_threshold: 5

zwave:
  usb_path: /dev/ttyACM0
  network_key: "0x82, 0x34, 0xC6, 0x24, 0x6E, 0xCF, 0x96, 0xDA, 0x49, 0xC4, 0xFA, 0xE3, 0x6C, 0x38, 0x14, 0xB4"

verisure:
  username: !secret vsure_user
  password: !secret vsure_pass

maxcube:
  gateways:
    - host: 192.168.1.183
      port: 62910

device_tracker:
  - platform: gpslogger
    password: !secret ha_dash_pw

#  - platform: nmap_tracker
#    hosts: 192.168.1.0/24
    
#  - platform: thomson
#    host: !secret my_thomson_ip
#    username: !secret my_thomson_user
#    password: !secret my_thomson_passw

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

recorder:
  purge_keep_days: 8

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

zone: !include zones.yaml

# Text to speech
#tts:
#  - platform: google

# Cloud
#cloud:

group: !include groups.yaml
script: !include scripts.yaml

input_select:
  dishwasher_status:
    name: Diskmaskin Status
    options:
      - Dirty
      - Running
      - Drying
      - Clean
    initial: Dirty

sensor: !include sensors.yaml
switch: !include switches.yaml
light: !include lights.yaml
notify: !include notifications.yaml

binary_sensor: !include binary_sensors.yaml

automation: !include_dir_merge_list automations/

#alert: !include alerts.yaml

history_graph:
  gr1:
    name: Lampor
    entities:
      - light.staketbelysning
      - light.dammbelysning
      - light.citrusbelysning
    hours_to_show: 96
    refresh: 60
  gr2:
    name: Temperatur ute
    entities:
      - sensor.ute_temp
      - sensor.uterum_temp
      - sensor.annex_temp
      - sensor.garaget
    hours_to_show: 168
  gr3:
    name: Temperatur inne
    entities:
      - sensor.vinkallaren
      - sensor.vinkylen
    hours_to_show: 168
  gr4:
    name: Vatten temp
    entities:
      - sensor.temp1
      - sensor.temp2
      - sensor.temp3
      - sensor.temp4
      - sensor.ute_temp
    hours_to_show: 48
  gr5:
    name: Strömförbrukning
    entities:
      - sensor.fas_1
      - sensor.fas_2
      - sensor.fas_3
    hours_to_show: 48
