title: Mossaparken Avsome Home
resources:
  - url: /customcards/github/custom-cards/tracker-card.js?track=true
    type: module
  - url: /local/slider-entity-row.js
    type: js
  - url: /local/canvas-gauge-card.js
    type: module
  - url: /local/mini-graph-card-bundle.js?v=0.3.2
    type: module
#title: Home Assistant
views:
  - badges: []
    cards:
      - type: history-graph
        title: Belysning
        show_header_toggle: false
        entities:
          - light.staketbelysning
          - light.dammbelysning
          - light.citrusbelysning
          - light.fibaro_system_fgd212_dimmer_2_level_2
          - light.aeotec_zw111_nano_dimmer_level
        hours_to_show: 96
        refresh_interval: 60
      - type: entities
        title: Lampor
        show_header_toggle: false
        entities:
          - type: section
            label: Vardagsrum
          - light.fonsterlampor_v_rum
          - light.fonsterlampa_s_v_rum
          - light.fonsterlampa_n_v_rum
          - light.vitrinskapet
          - type: section
            label: Köket
          - light.koksfonstret
          - light.koksfonster
          - light.kokslampa_matbord
          - light.kokslampa_kokso
          - light.koksbank
          - type: custom:slider-entity-row
            entity: light.aeotec_zw111_nano_dimmer_level
            toggle: true
          - type: section
            label: Övriga
          - light.fonsterlampa_trappan
          - type: section
            label: Ute
          - type: custom:slider-entity-row
            entity: light.fibaro_system_fgd212_dimmer_2_level_2
            toggle: true
          - light.uterummet
          - light.staketbelysning
          - light.dammbelysning
          - light.citrusbelysning
      - type: entities
        title: Scener
        show_header_toggle: false
        entities:
          - scene.dinner
          - scene.night
          - scene.work
    path: lights_view
    title: Lampor
  - badges:
    cards:
      - entities:
          - sensor.dishwasher_status
          - sensor.diskmaskin_idag
          - sensor.diskmaskin_igar
          - sensor.diskmaskin_totalt
          - sensor.diskmaskin_effekt
          - sensor.diskmaskin_spanning
          - sensor.diskmaskin_strom
        show_header_toggle: false
        title: Diskmaskinen
        type: entities
      - entities:
          - sensor.effekt_idag
          - sensor.effekt_igar
          - sensor.effekt_totalt
          - sensor.effekt_nu
          - sensor.element_spanning
          - sensor.element_strom
        show_header_toggle: false
        title: Citruselementen
        type: entities
      - entities:
          - sensor.fas_1
          - sensor.fas_2
          - sensor.fas_3
          - sensor.effekt_1
          - sensor.effekt_2
          - sensor.effekt_3
          - sensor.forbrukning_idag
          - sensor.veckoforbrukning
          - sensor.manadsforbrukning
          - sensor.arsforbrukning
        show_header_toggle: true
        title: Förbrukning huset
        type: entities
    path: devices_view
    title: Apparater
  - badges:
    cards:
      - type: custom:mini-graph-card
        name: Ström
        icon: mdi:server
        entities:
          - sensor.fas_1
          - sensor.fas_2
          - sensor.fas_3
      - type: custom:canvas-gauge-card
        entity: sensor.fas_1
        name: Fas 1 (A)
        card_height: 145
        shadow_height: 15%
        font_size: 1em
        gauge:
          type: "radial-gauge"
          width: 220
          height: 220
          minValue: 0
          maxValue: 30
          startAngle: 90
          ticksAngle: 180
          valueBox: false
          majorTicks: ["0", "5", "10", "15", "20", "25", "30"]
          minorTicks: 2
          strokeTicks: true
          highlights: [{"from": 0, "to": 10,"color": "rgba(46, 204, 113, .75)"},{"from": 10, "to": 20,"color": "rgba(241, 196, 15, .75)"},{"from": 20, "to": 30,"color": "rgba(211, 84, 0, .75)"}]
          borders: false
      - type: custom:canvas-gauge-card
        entity: sensor.fas_2
        name: Fas 2 (A)
        card_height: 145
        shadow_height: 15%
        font_size: 1em
        gauge:
          type: "radial-gauge"
          width: 220
          height: 220
          minValue: 0
          maxValue: 30
          startAngle: 90
          ticksAngle: 180
          valueBox: false
          majorTicks: ["0", "5", "10", "15", "20", "25", "30"]
          minorTicks: 2
          strokeTicks: true
          highlights: [{"from": 0, "to": 10,"color": "rgba(46, 204, 113, .75)"},{"from": 10, "to": 20,"color": "rgba(241, 196, 15, .75)"},{"from": 20, "to": 30,"color": "rgba(211, 84, 0, .75)"}]
          borders: false
      - type: custom:canvas-gauge-card
        entity: sensor.fas_3
        name: Fas 3 (A)
        card_height: 145
        shadow_height: 15%
        font_size: 1em
        gauge:
          type: "radial-gauge"
          width: 220
          height: 220
          minValue: 0
          maxValue: 30
          startAngle: 90
          ticksAngle: 180
          valueBox: false
          majorTicks: ["0", "5", "10", "15", "20", "25", "30"]
          minorTicks: 2
          strokeTicks: true
          highlights: [{"from": 0, "to": 10,"color": "rgba(46, 204, 113, .75)"},{"from": 10, "to": 20,"color": "rgba(241, 196, 15, .75)"},{"from": 20, "to": 30,"color": "rgba(211, 84, 0, .75)"}]
          borders: false
    path: current_view
    title: Ström
  - badges:
      - binary_sensor.workday_today
      - binary_sensor.workday_tomorrow
      - binary_sensor.vaderstation
      - binary_sensor.cisco
      - binary_sensor.d_link
      - binary_sensor.tigerwolf
      - binary_sensor.unify
      - binary_sensor.eddieserver
      - binary_sensor.telia
      - binary_sensor.entre
      - binary_sensor.altandorr
      - binary_sensor.terass
      - binary_sensor.kallardorr
      - binary_sensor.aeotec_zw100_multisensor_6_sensor_3
      - binary_sensor.fibaro_system_fgms001zw5_motion_sensor_sensor
      - binary_sensor.aeotec_zw100_multisensor_6_sensor_4
      - device_tracker.bh9000mba2
      - device_tracker.android4f3fd99304357839lan
      - device_tracker.androidb03b56dedfc413e5lan
      - device_tracker.androide39fdb334674e99blan
      - device_tracker.84c7ea8b5250
      - sensor.online
      - sensor.phone_battery
      - sensor.phone_altitude
      - sensor.dishw_status
      - sensor.fas_1_status
      - sensor.fas_2_status
      - sensor.fas_3_status
      - sensor.citrus_belysningen
      - sensor.garaget
      - sensor.vinkallaren
      - sensor.vinkylen
      - sensor.garageport_norr
      - sensor.temp1
      - sensor.temp2
      - sensor.temp3
      - sensor.temp4
      - sensor.spa_temp
      - sensor.spa
      - sensor.nodeit_temp
      - sensor.julgran
      - sensor.annex_ljus
      - sensor.kok_temperature
      - sensor.custom_component_tracker
      - sensor.aeotec_zw100_multisensor_6_temperature_3
      - sensor.aeotec_zw100_multisensor_6_luminance_3
      - sensor.aeotec_zw100_multisensor_6_relative_humidity_3
      - sensor.aeotec_zw100_multisensor_6_ultraviolet_3
      - sensor.aeotec_zw100_multisensor_6_burglar_3
      - sensor.fibaro_system_fgd212_dimmer_2_power_2
      - sensor.fibaro_system_fgd212_dimmer_2_energy
      - sensor.fibaro_system_fgms001zw5_motion_sensor_temperature
      - sensor.fibaro_system_fgms001zw5_motion_sensor_luminance
      - sensor.fibaro_system_fgms001zw5_motion_sensor_seismic_intensity
      - sensor.fibaro_system_fgms001zw5_motion_sensor_burglar
      - sensor.fibaro_system_fgms001zw5_motion_sensor_general
      - sensor.aeotec_zw111_nano_dimmer_energy
      - sensor.aeotec_zw111_nano_dimmer_power
      - sensor.aeotec_zw100_multisensor_6_temperature_4
      - sensor.aeotec_zw100_multisensor_6_luminance_4
      - sensor.aeotec_zw100_multisensor_6_relative_humidity_4
      - sensor.aeotec_zw100_multisensor_6_ultraviolet_4
      - sensor.aeotec_zw100_multisensor_6_burglar_4
    cards:
      - entities:
          - sensor.dishwasher_status
          - sensor.diskmaskin_idag
          - sensor.diskmaskin_igar
          - sensor.diskmaskin_totalt
          - sensor.diskmaskin_effekt
          - sensor.diskmaskin_spanning
          - sensor.diskmaskin_strom
        show_header_toggle: false
        title: Diskmaskinen
        type: entities
      - entities:
          - sensor.effekt_idag
          - sensor.effekt_igar
          - sensor.effekt_totalt
          - sensor.effekt_nu
          - sensor.element_spanning
          - sensor.element_strom
        show_header_toggle: false
        title: Citruselementen
        type: entities
      - entities:
          - sensor.garage_door_state
        show_header_toggle: true
        title: Garaget
        type: entities
      - entities:
          - sensor.dark_sky_summary
          - sensor.ute_temp
          - sensor.dark_sky_temperature
          - sensor.annex_temp
          - sensor.uterum_temp
          - sensor.ute_tryck
          - sensor.annex_humid
          - sensor.dark_sky_humidity
        show_header_toggle: true
        title: Väder
        type: entities
      - entities:
          - sensor.fas_1
          - sensor.fas_2
          - sensor.fas_3
          - sensor.effekt_1
          - sensor.effekt_2
          - sensor.effekt_3
          - sensor.forbrukning_idag
          - sensor.veckoforbrukning
          - sensor.manadsforbrukning
          - sensor.arsforbrukning
        show_header_toggle: true
        title: Förbrukning huset
        type: entities
      - entities:
          - sun.sun
          - sensor.moon
          - sensor.season
          - sensor.dark_sky_summary
          - sensor.dark_sky_precip
          - sensor.dark_sky_precip_intensity
          - sensor.dark_sky_precip_probability
          - sensor.dark_sky_temperature
          - sensor.dark_sky_apparent_temperature
          - sensor.dark_sky_wind_speed
          - sensor.dark_sky_wind_bearing
          - sensor.dark_sky_humidity
        show_header_toggle: true
        title: Vädret nu
        type: entities
      - entities:
          - sensor.forecast_0
          - sensor.forecast_1
          - sensor.forecast_2
          - sensor.forecast_3
          - sensor.forecast_4
          - sensor.forecast_5
          - sensor.forecast_6
          - sensor.forecast_7
        show_header_toggle: true
        title: Prognos
        type: entities
      - entity: alarm_control_panel.hemma_alarm
        type: alarm-panel
      - entities:
          - automation.phase2high
          - automation.phase3high
          - automation.vinkallaretemp
          - automation.vinkyltemp
          - automation.lag_temp_i_annexet
          - automation.power_house
          - automation.lag_temp_i_garaget
          - automation.house_kwh_new_month
          - automation.notify_if_ha_device_offline
          - automation.kokslampan_pa_morgon
          - automation.citrusbelysning_pa
          - automation.kokslampan_av_morgon
          - automation.citrusbelysning_av
          - automation.kokslampan_pa_kvall
          - automation.citruselement_pa
          - automation.kokslampan_av_kvall
          - automation.citruselement_av
          - automation.vardagsrumslampan_pa
          - automation.tradgardsbelysningen_pa_vid_solnedgang
          - automation.vardagsrumslampan_av
          - automation.tradgardsbelysningen_av_vardag
          - automation.vitrinskapet_pa
          - automation.tradgardsbelysningen_av_helgen
          - automation.vitrinskapet_av_vardag
          - automation.dammbelysningen_pa_morgon
          - automation.vitrinskapet_av_helg
          - automation.dammbelysningen_av_morgon
          - automation.trapplampan_pa_morgon
          - automation.dammbelysningen_pa_vid_solnedgang
          - automation.trapplampan_av_morgon
          - automation.dammbelysningen_av_kvall
          - automation.trapplampan_pa_kvall
          - automation.dammpumpen_pa_kvall
          - automation.trapplampan_av_kvall
          - automation.dammpumpen_av_kvall
          - automation.set_dishwasher_active_when_power_detected
          - automation.rorelse_i_garaget
          - automation.set_dishwasher_drying_when_power_drops
          - automation.nagon_i_garaget
          - automation.set_dishwasher_clean
          - automation.ingen_i_garaget_slack_efter_nagra_minuter
          - automation.set_dishwasher_dirty_when_power_off
          - automation.nagon_i_annexet
          - automation.send_alert_when_dishwasher_is_clean
          - automation.alarm_fran_garaget
          - automation.notify_if_ha_device_offline_2
          - automation.spatemplow
          - automation.spatemphigh
          - automation.phase1high
        title: Automation
        type: entities
      - entity: camera.o_van
        type: picture-entity
      - entity: climate.gillestugan_radiator_thermostat_1
        type: thermostat
      - entity: climate.vardagsrummet_radiator_norr
        type: thermostat
      - entity: climate.koket_radiator_thermostat_1
        type: thermostat
      - entity: climate.badrum_ovanvan_radiator_thermostat_1
        type: thermostat
      - entity: climate.badrum_van_1_radiator_thermostat_1
        type: thermostat
      - entity: climate.hallen_radiator_thermostat_1
        type: thermostat
      - entity: climate.vardagsrummet_radiator_soder
        type: thermostat
      - entity: climate.sovrummet_radiator_thermostat_1
        type: thermostat
      - entity: climate.vardagsrummet_vaggtermostat
        type: thermostat
      - entities:
          - entity_controller.rorelse_i_garaget
          - entity_controller.rorelse_i_annexet
        title: ''
        type: entities
      - entities:
          - sensor.vinkallaren
          - sensor.vinkylen
        hours_to_show: 168
        refresh_interval: 0
        title: Temperatur inne
        type: history-graph
      - entities:
          - sensor.julgran
        hours_to_show: 168
        refresh_interval: 0
        title: Julgranen
        type: history-graph
      - entities:
          - sensor.ute_temp
          - sensor.uterum_temp
          - sensor.annex_temp
          - sensor.garaget
        hours_to_show: 168
        refresh_interval: 0
        title: Temperatur ute
        type: history-graph
      - entities:
          - sensor.fas_1
          - sensor.fas_2
          - sensor.fas_3
        hours_to_show: 48
        refresh_interval: 0
        title: Strömförbrukning
        type: history-graph
      - entities:
          - light.staketbelysning
          - light.dammbelysning
          - light.citrusbelysning
        hours_to_show: 96
        refresh_interval: 60
        title: Lampor
        type: history-graph
      - entities:
          - sensor.temp1
          - sensor.temp2
          - sensor.temp3
          - sensor.temp4
          - sensor.ute_temp
        hours_to_show: 48
        refresh_interval: 0
        title: Vatten temp
        type: history-graph
      - entities:
          - input_select.dishwasher_status
        title: Välj
        type: entities
      - entities:
          - light.fonsterlampor_v_rum
          - light.fonsterlampa_s_v_rum
          - light.fonsterlampa_n_v_rum
          - light.vitrinskapet
          - light.fonsterlampa_trappan
          - light.koksfonstret
          - light.fibaro_system_fgd212_dimmer_2_level_2
          - light.aeotec_zw111_nano_dimmer_level
          - light.uterummet
          - light.kokslampa_matbord
          - light.staketbelysning
          - light.dammbelysning
          - light.citrusbelysning
        title: Lampor
        type: entities
      - entity: media_player.volumio_mossamusic_local
        type: media-control
      - entities:
          - switch.spa_over
          - switch.spa_under
          - switch.dammpump
          - switch.citruselementet
          - switch.aeotec_zw111_nano_dimmer_switch
        title: Kontakt
        type: entities
      - entities:
          - zwave.zwaveme_zme_uzb1_usb_stick
          - zwave.fibaro_system_fgms001zw5_motion_sensor
          - zwave.aeotec_zw111_nano_dimmer
        title: Z-Wave
        type: entities
      - type: 'custom:tracker-card'
    path: default_view
    title: Home
  - badges: []
    cards:
      - entities:
          - sun.sun
          - sensor.moon
          - sensor.season
          - sensor.dark_sky_summary
          - sensor.dark_sky_precip
          - sensor.dark_sky_precip_type
          - sensor.dark_sky_precip_intensity
          - sensor.dark_sky_precip_probability
          - sensor.dark_sky_temperature
          - sensor.dark_sky_apparent_temperature
          - sensor.dark_sky_wind_speed
          - sensor.dark_sky_wind_bearing
          - sensor.dark_sky_cloud_cover
          - sensor.dark_sky_humidity
        show_header_toggle: true
        title: Vädret nu
        type: entities
      - entities:
          - sensor.forecast_0
          - sensor.forecast_1
          - sensor.forecast_2
          - sensor.forecast_3
          - sensor.forecast_4
          - sensor.forecast_5
          - sensor.forecast_6
          - sensor.forecast_7
        show_header_toggle: true
        title: Prognos
        type: entities
    icon: 'mdi:weather-sunset'
    path: weather_tab
    title: Weather
