sensor.aeotec_zw100_multisensor_6_alarm_level_3:
  ignored: true
  polling_intensity: 0
sensor.aeotec_zw100_multisensor_6_alarm_type_3:
  ignored: true
  polling_intensity: 0
sensor.aeotec_zw100_multisensor_6_sourcenodeid_3:
  ignored: true
  polling_intensity: 0
sensor.aeotec_zw100_multisensor_6_luminance_3:
  ignored: false
  polling_intensity: 0
