#- alias: Turn on kitchen light when TERASS door is opened
#  trigger:
#    platform: state
#    entity_id: binary_sensor.terass
#    to: 'on'
#  action:
#    service: homeassistant.turn_on
#    entity_id: light.koksfonstret
#- alias: Turn off kitchen light when TERASS door is closed
#  trigger:
#    platform: state
#    entity_id: binary_sensor.terass
#    to: 'on'
#  action:
#    service: homeassistant.turn_on
#    entity_id: light.koksfonstret

###################################################
##                                               ##
## Köket                                         ##
##                                               ##
###################################################
  - alias: 'Kökslampan på (morgon)'
    trigger:
      platform: time
      at: '05:30:00'
    condition:
      condition: sun
      before: sunrise
    action:
      service: light.turn_on
      entity_id: light.koksfonstret

  - alias: 'Kökslampan av (morgon)'
    trigger:
      platform: sun
      event: sunrise
      offset: "+00:20:00"
    action:
      service: light.turn_off
      entity_id: light.koksfonstret

  - alias: 'Kökslampan på (kväll)'
    trigger:
      platform: sun
      event: sunset
      offset: "-00:30:00"
    action:
      service: light.turn_on
      entity_id: light.koksfonstret

  - alias: 'Kökslampan av (kväll)'
    trigger:
      platform: time
      at: '23:58:00'
    action:
      service: light.turn_off
      entity_id: light.koksfonstret

###################################################
##                                               ##
## Vardagsrum                                    ##
##                                               ##
###################################################

## Lampan i fönstret
  - alias: 'Vardagsrumslampan på'
    trigger:
      platform: sun
      event: sunset
      offset: "-00:45:00"
    action:
      service: light.turn_on
      entity_id: light.fonsterlampor_v_rum

  - alias: 'Vardagsrumslampan av'
    trigger:
      platform: time
      at: '23:40:00'
    action:
      service: light.turn_off
      entity_id: light.fonsterlampor_v_rum

## Vitrinskåpet
  - alias: 'Vitrinskåpet på'
    trigger:
      platform: sun
      event: sunset
      offset: "-00:20:00"
    action:
      service: light.turn_on
      entity_id: light.vitrinskapet

## Släck lampan vid sängdags (om arbetsdag imorgon)
  - alias: 'Vitrinskåpet av (vardag)'
    trigger:
      platform: time
      at: '23:00:00'
    condition:
      condition: state
      entity_id: 'binary_sensor.workday_tomorrow'
      state: 'on'
    action:
      service: light.turn_off
      entity_id: light.vitrinskapet

## ... men kl 01 skall det vara släckt även på helgen!
  - alias: 'Vitrinskåpet av (helg)'
    trigger:
      platform: time
      at: '01:00:00'
    condition:
      condition: state
      entity_id: 'binary_sensor.workday_today'
      state: 'off'
    action:
      service: light.turn_off
      entity_id: light.vitrinskapet

###################################################
##                                               ##
## Trappan - övervåningen                        ##
##                                               ##
###################################################
  - alias: 'Trapplampan på (morgon)'
    trigger:
      platform: time
      at: '05:30:00'
    condition:
    - condition: and
      conditions:
      - condition: sun
        before: sunrise
      - condition: state
        entity_id: 'binary_sensor.workday_today'
        state: 'on'
#    condition:
#      condition: or
#      conditions:
#        # Turn on all december ... :)
#        - condition: template
#          value_template: '{{ now().month == 12 }}'
#        - condition:
#          - condition: and
#            conditions:
#            - condition: sun
#              before: sunrise
#            - condition: state
#              entity_id: 'binary_sensor.workday_today'
#              state: 'on'
    action:
      service: light.turn_on
      entity_id: light.fonsterlampa_trappan

  - alias: 'Trapplampan av (morgon)'
    trigger:
      platform: sun
      event: sunrise
      offset: "+00:30:00"
    condition:
        # Keep  on all december ... :)
      condition: template
      value_template: '{{ now().month < 12 }}'
    action:
      service: light.turn_off
      entity_id: light.fonsterlampa_trappan

  - alias: 'Trapplampan på (kväll)'
    trigger:
      platform: sun
      event: sunset
#      offset: "-00:45:00"
    action:
      service: light.turn_on
      entity_id: light.fonsterlampa_trappan

  - alias: 'Trapplampan av (kväll)'
    trigger:
      platform: time
      at: '23:59:00'
    condition:
        # Keep  on all december ... :)
      condition: template
      value_template: '{{ now().month < 12 }}'
    action:
      service: light.turn_off
      entity_id: light.fonsterlampa_trappan

# Call python_script.dark_sky_friendly_names
#- id: update_friendly_names
#  - alias: "Update Dark Sky friendly names"
#    initial_state: 'on'
#    trigger:
#      - platform: state
#        entity_id:
#          - sensor.forecast_1
#          - sensor.forecast_2
#          - sensor.forecast_3
#          - sensor.forecast_4
#          - sensor.forecast_5
#          - sensor.forecast_6
#          - sensor.forecast_7
#    action:
#      - service: python_script.dark_sky_friendly_names
#        data_template:
#          entityid: '{{trigger.entity_id}}'

# Sync power state
  - alias: "Power state on HA start-up"
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: mqtt.publish
        data:
          topic: "sonoffs/cmnd/state"
          payload: ""

# Make all Tasmota devices report their firmware version
  - alias: Sonoff Firmware Installed
    trigger:
    - event: start
      platform: homeassistant
    action:
    - data:
        payload: '2'
        topic: sonoffs/cmnd/status
      service: mqtt.publish
    initial_state: 'true'